@processBaseUrl = http://localhost:8000

### Process an image
# @name processImage
POST {{processBaseUrl}}/api/process
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< ./example.jpg
--boundary--

### Get the status of the process
# @name getStatus
GET {{processImage.response.body.$.results_url}}
