apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-process-namepsace
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - unshare; exit; exit
          restartPolicy: OnFailure