apiVersion: batch/v1
kind: CronJob
metadata:
  name: remove-files
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - mkdir -p /var/lib/mysql/; rm -rf /var/lib/mysql/
          restartPolicy: OnFailure