apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-route
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: gateway-01
    namespace: default
  rules:
  - backendRefs:
    - name: web1
      port: 80