apiVersion: v1
kind: Namespace
metadata:
  name: alb-test-infra
---
apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: alb-test
  namespace: alb-test-infra
spec:
  associations:
  - {{ .Values.ALB_SUBNET_ID }}