apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: canary-demo
            port:
              number: 80
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: canary-demo
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: canary.{{ .Values.externalIp }}.nip.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend: 
#           service:
#             name: canary-demo
#             port:
#               number: 80
