apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: canary.{{ .Values.externalIp }}.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: canary-demo
            port:
              number: 80
