apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo-preview
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: canary-preview.{{ .Values.externalIp }}.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          services:
            name: canary-demo-preview
            port:
              number: 80
