apiVersion: v1
kind: ConfigMap
metadata:
  name: fio
  namespace: acstor-local
data:
  sync-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  sync-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  async-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  async-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  large-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [writer1]
    rw=randwrite
    directory=/data
  large-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [reader1]
    rw=randread
    directory=/data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio
  namespace: acstor-disk
data:
  sync-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  sync-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  async-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  async-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  large-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [writer1]
    rw=randwrite
    directory=/data
  large-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [reader1]
    rw=randread
    directory=/data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio
  namespace: manual-local
data:
  sync-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  sync-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  async-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  async-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  large-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [writer1]
    rw=randwrite
    directory=/data
  large-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [reader1]
    rw=randread
    directory=/data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio
  namespace: csi-disk
data:
  sync-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  sync-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=1
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  async-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [writer1]
    rw=randwrite
    directory=/data
  async-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k

    [reader1]
    rw=randread
    directory=/data
  large-w.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [writer1]
    rw=randwrite
    directory=/data
  large-r.ini: |
    [global]
    size=30g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=1M

    [reader1]
    rw=randread
    directory=/data