kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: premium-zrs
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_ZRS 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer