kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: premiumv2-lrs
provisioner: disk.csi.azure.com
parameters:
  skuname: PremiumV2_LRS 
  DiskIOPSReadWrite: "5000"
  DiskMBpsReadWrite: "200"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer