[project]
name = "d-ai-token-visualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.23.0",
    "openai>=1.92.2",
    "python-dotenv>=1.1.1",
]
