{
 "title": "Azure Network Policy Manager Configuration (Prometheus Server)",
 "description": "Monitor and understand your Network Configuration. Uses a Prometheus Server data source.",
 "tags": [
  "Azure NPM",
  "Azure Container Insights",
  "Azure Monitor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(npm_add_policy_exec_time, instance)"
   },
   {
    "name": "quantiles",
    "label": "Runtime Quantiles",
    "query": "label_values(npm_add_policy_exec_time, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "Current Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "npm_num_policies\n" }
   ]
  },
  {
   "title": "IPTables Rules",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "npm_num_iptables_rules" }
   ]
  },
  {
   "title": "IPSets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "npm_num_ipsets" }
   ]
  },
  { "title": "Counts Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Network Policies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "npm_num_policies", "legendFormat": " " }
   ]
  },
  {
   "title": "IPTables Rules",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "npm_num_iptables_rules", "legendFormat": " " }
   ]
  },
  {
   "title": "IPSets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "npm_num_ipsets", "legendFormat": " " }
   ]
  },
  { "title": "IPSet Entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total Entries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "npm_num_ipset_entries" }
   ]
  },
  {
   "title": "Entries per IPSet",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sort_desc(sum(npm_ipset_counts) by (set_name, set_hash) != 0)"
    }
   ]
  },
  {
   "title": "Runtime (select quantile at top)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Add Policy Runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "npm_add_policy_exec_time{instance=\"$instance\",quantile=~\"$quantiles\"}",
     "legendFormat": "{{quantile}}'th quantile"
    }
   ]
  },
  {
   "title": "Add IPTables Rule Runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "npm_add_iptables_rule_exec_time{instance=\"$instance\",quantile=~\"$quantiles\"}",
     "legendFormat": "{{quantile}}'th quantile"
    }
   ]
  },
  {
   "title": "Add IPSet Runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "npm_add_ipset_exec_time{instance=\"$instance\",quantile=~\"$quantiles\"}",
     "legendFormat": "{{quantile}}'th quantile"
    }
   ]
  }
 ]
}