[project]
name = "github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.21.0",
    "mcp>=1.6.0",
    "python-dotenv>=1.1.0",
    "semantic-kernel>=1.28.1",
]
