apiVersion: apps/v1
kind: Deployment
metadata:
  name: T01-A-app1
  namespace: T01-A
spec:
  replicas: 1
  selector:
    matchLabels:
      app: T01-A-app1
  template:
    metadata:
      labels:
        app: T01-A-app1
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "64Mi"
            cpu: "180m"
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: T01-A-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T01-A-app2
  namespace: T01-A
spec:
  replicas: 3
  selector:
    matchLabels:
      app: T01-A-app2
  template:
    metadata:
      labels:
        app: T01-A-app2
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "80m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T01-B-app1
  namespace: T01-B
spec:
  replicas: 1
  selector:
    matchLabels:
      app: T01-B-app1
  template:
    metadata:
      labels:
        app: T01-B-app1
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "80m"
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: T01-B-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T01-B-app2
  namespace: T01-B
spec:
  replicas: 4
  selector:
    matchLabels:
      app: T01-B-app2
  template:
    metadata:
      labels:
        app: T01-B-app2
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "96Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "180m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T02-A-app1
  namespace: T02-A
spec:
  replicas: 1
  selector:
    matchLabels:
      app: T02-A-app1
  template:
    metadata:
      labels:
        app: T02-A-app1
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "280m"
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: T02-A-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T02-A-app2
  namespace: T02-A
spec:
  replicas: 4
  selector:
    matchLabels:
      app: T02-A-app2
  template:
    metadata:
      labels:
        app: T02-A-app2
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "64Mi"
            cpu: "180m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T02-B-app1
  namespace: T02-B
spec:
  replicas: 1
  selector:
    matchLabels:
      app: T02-B-app1
  template:
    metadata:
      labels:
        app: T02-B-app1
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "180m"
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: T02-B-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: T02-B-app2
  namespace: T02-B
spec:
  replicas: 2
  selector:
    matchLabels:
      app: T02-B-app2
  template:
    metadata:
      labels:
        app: T02-B-app2
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "64Mi"
            cpu: "180m"
