apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace1
---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace2
---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace3
---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace4
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: mynamespace1
  labels:
    app: component1
    solution: solution1
    environment: prod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: mynamespace2
  labels:
    app: component2
    solution: solution1
    environment: prod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: mynamespace1
  labels:
    app: component1
    solution: solution1
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  namespace: mynamespace3
  labels:
    app: component1
    solution: solution2
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod5
  namespace: mynamespace2
  labels:
    app: component5
    solution: solution2
    environment: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod6
  namespace: mynamespace2
  labels:
    app: component2
    solution: solution1
    environment: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod8
  namespace: mynamespace2
  labels:
    app: component6
    solution: solution2
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod9
  namespace: mynamespace2
  labels:
    app: component1
    solution: solution3
    environment: prod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod10
  namespace: mynamespace3
  labels:
    app: component1
    solution: solution2
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi