$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Tomas lendingclub demo pipeline

display_name: lendingclub-demo-training
experiment_name: lendingclub-demo-training

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:managed-cluster

jobs:
  prepare_data:
    inputs:
      raw_data:
        type: uri_file
        path: azureml:lending_club_raw:1
        mode: ro_mount 
    type: command
    component: file:../components/lending_club_process_data/component.yaml
    outputs:
      processed_data:
  split:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.prepare_data.outputs.processed_data}}
        mode: ro_mount 
      label_name: loan_repaid
      file_name: lending_club.csv
      test_size: 0.2
    type: command
    component: azureml:split@latest
    outputs:
      train:
      test:
  scale:
    inputs:
      train_input:
        type: uri_file
        path: ${{parent.jobs.split.outputs.train}}
        mode: ro_mount 
      test_input:
        type: uri_file
        path: ${{parent.jobs.split.outputs.test}}
        mode: ro_mount 
    type: command
    component: azureml:scale@latest
    outputs:
      train:
      test:
      scaler:
  oversample:
    inputs:
      train_input:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.train}}
        mode: ro_mount 
    type: command
    component: azureml:oversample@latest
    outputs:
      train:
  reference_model:
    inputs:
      train_input:
        type: uri_file
        path: ${{parent.jobs.oversample.outputs.train}}
        mode: ro_mount 
      test_input:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.test}}
        mode: ro_mount 
    type: command
    component: azureml:reference_model_always_one@latest
  train_lr:
    inputs:
      train_input:
        type: uri_file
        path: ${{parent.jobs.oversample.outputs.train}}
        mode: ro_mount 
      test_input:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.test}}
        mode: ro_mount 
      saved_scaler:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.scaler}}
        mode: ro_mount 
    outputs:
      finished: 
    type: sweep
    objective:
      goal: maximize
      primary_metric: training_accuracy_score
    sampling_algorithm: grid
    search_space:
      solver:
        type: choice
        values: ['lbfgs', 'sag', 'saga', 'newton-cg']
    trial: ../components/lending_club_train_lr/component.yaml
    limits:
      max_total_trials: 10
      max_concurrent_trials: 10
      timeout: 7200
  train_lightgbm:
    inputs:
      train_input:
        type: uri_file
        path: ${{parent.jobs.oversample.outputs.train}}
        mode: ro_mount 
      test_input:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.test}}
        mode: ro_mount 
      saved_scaler:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.scaler}}
        mode: ro_mount 
    outputs:
      finished: 
    type: sweep
    objective:
      goal: maximize
      primary_metric: training_accuracy_score
    sampling_algorithm: random
    search_space:
      num_leaves:
        type: randint
        upper: 1000
    trial: ../components/lending_club_train_lightgbm/component.yaml
    limits:
      max_total_trials: 5
      max_concurrent_trials: 10
      timeout: 7200
  train_tensorflow:
    inputs:
      train_input:
        type: uri_file
        path: ${{parent.jobs.oversample.outputs.train}}
        mode: ro_mount 
      test_input:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.test}}
        mode: ro_mount 
      saved_scaler:
        type: uri_file
        path: ${{parent.jobs.scale.outputs.scaler}}
        mode: ro_mount 
    outputs:
      finished: 
    type: sweep
    objective:
      goal: maximize
      primary_metric: val_accuracy
    sampling_algorithm: grid
    search_space:
      dropout:
        type: choice
        values: [0.01, 0.1, 0.2, 0.5]
    trial: ../components/lending_club_train_tensorflow/component.yaml
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200
  register_best_model:
    inputs:
      start_lr: ${{parent.jobs.train_lr.outputs.finished}}
      start_tensorflow: ${{parent.jobs.train_tensorflow.outputs.finished}}
      start_lightgbm: ${{parent.jobs.train_lightgbm.outputs.finished}}
    type: command
    component: azureml:register_best_model@latest