$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Tomas lendingclub demo pipeline

display_name: lendingclub-demo-pipeline
experiment_name: lendingclub-demo-experiment

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:managed-cluster

jobs:
  prepare_data:
    inputs:
      raw_data:
        type: uri_file
        path: azureml:lending_club_raw:1
        mode: ro_mount 
    type: command
    component: azureml:lending_club_process_data@latest
    outputs:
      processed_data:
  split_and_scale:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.prepare_data.outputs.processed_data}}
        mode: ro_mount 
      label_name: loan_repaid
      file_name: landing_club_processed.csv
    type: command
    component: azureml:split_and_scale@latest
    outputs:
      datasets:
  reference_model:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.split_and_scale.outputs.datasets}}
        mode: ro_mount 
    type: command
    component: azureml:reference_model_always_one@latest
  train_lr:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.split_and_scale.outputs.datasets}}
        mode: ro_mount 
    type: sweep
    objective:
      goal: maximize
      primary_metric: training_accuracy_score
    sampling_algorithm: grid
    search_space:
      solver:
        type: choice
        values: ['lbfgs', 'sag', 'saga', 'newton-cg']
    trial: ../components/lending_club_train_lr/component.yaml
    limits:
      max_total_trials: 10
      max_concurrent_trials: 10
      timeout: 7200
  train_tensorflow:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.split_and_scale.outputs.datasets}}
        mode: ro_mount 
    type: sweep
    objective:
      goal: maximize
      primary_metric: val_accuracy
    sampling_algorithm: grid
    search_space:
      dropout:
        type: choice
        values: [0.01, 0.1, 0.2, 0.5]
    trial: ../components/lending_club_train_tensorflow/component.yaml
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200