trim_configs:
  - size: 100
    filename: "train_100.csv"
  - size: 1000
    filename: "train_1000.csv"
  - size: "all"
    filename: "train_all.csv"

# Column configurations
text_column: "text"
label_column: "label"

# Random seed for reproducibility
random_seed: 42

# Output directory
output_dir: "train"

# Input file (can be overridden by command line)
input_file: "dataset/train_df.csv"
